server.port: 8080
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_db
    username: root
    password:
#coherence:
#  distributed:
#    persistence:
#      mode: active
#      base:
#       dir: "E:/2022-workspace/coherence/Commands&Logs/fault-tolerant"
  lambdas: static